# Generated by Django 5.2 on 2025-05-02 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capybara_countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Local')),
                ('order', models.SmallIntegerField(db_index=True, default=0, verbose_name='Order')),
                ('slug', models.SlugField(max_length=30, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='SubLocal',
            fields=[
            ],
            options={
                'verbose_name': 'Sub Local',
                'verbose_name_plural': 'Sub Locals',
                'ordering': ['super_Local__order', 'super_Local__name', 'order', 'name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('capybara_countries.local',),
        ),
        migrations.CreateModel(
            name='SuperLocal',
            fields=[
            ],
            options={
                'verbose_name': 'Super Local',
                'verbose_name_plural': 'Super Locals',
                'ordering': ['order', 'name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('capybara_countries.local',),
        ),
        migrations.AddField(
            model_name='local',
            name='super_Local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_local', to='capybara_countries.superlocal', verbose_name='Super Local'),
        ),
    ]
