# Generated by Django 5.2 on 2025-05-02 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capybara_categories', '0003_rubric_subrubric_superrubric_rubric_super_rubric'),
        ('capybara_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='capybara_categories.rubric', verbose_name='Category'),
        ),
    ]
