# Generated by Django 5.2 on 2025-04-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capybara_products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_main',
        ),
    ]
