# Generated by Django 5.2 on 2025-04-20 17:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capybara_products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpremium',
            options={'ordering': ['-end_date'], 'verbose_name': 'Product premium', 'verbose_name_plural': 'Product premiums'},
        ),
        migrations.AlterField(
            model_name='productpremium',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment ID'),
        ),
        migrations.AlterField(
            model_name='productpremium',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_product', to='capybara_products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productpremium',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date'),
        ),
    ]
