# Generated by Django 5.2 on 2025-04-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capybara_products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='is_active',
        ),
        migrations.AddField(
            model_name='productcomment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Не проверено'), (1, 'Одобрено'), (2, 'Отклонено'), (3, 'Опубликовано'), (4, 'Архив')], default=0, verbose_name='Status'),
        ),
    ]
