# Generated by Django 5.2 on 2025-05-02 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capybara_categories', '0003_rubric_subrubric_superrubric_rubric_super_rubric'),
        ('capybara_countries', '0002_local_sublocal_superlocal_local_super_local'),
        ('capybara_products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='capybara_categories.subrubric', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_by_city', to='capybara_countries.sublocal', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_by_country', to='capybara_countries.superlocal', verbose_name='Country'),
        ),
    ]
