# Generated by Django 5.2 on 2025-04-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capybara_products', '0003_alter_productpremium_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=550, verbose_name='Description'),
        ),
    ]
