# Generated by Django 5.2 on 2025-05-04 17:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capybara_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('duration_days', models.IntegerField(verbose_name='Duration (days)')),
                ('price', models.ImageField(default=0, upload_to='', verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Premium plan',
                'verbose_name_plural': 'Premium plans',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capybara_premium.premiumplan', verbose_name='Premium plan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_product', to='capybara_products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product premium',
                'verbose_name_plural': 'Product premiums',
                'ordering': ['-end_date'],
            },
        ),
    ]
