# Generated by Django 5.2 on 2025-05-04 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capybara_premium', '0001_initial'),
        ('capybara_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpremium',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_product', to='capybara_products.product', verbose_name='Product'),
        ),
    ]
