# Generated by Django 5.2 on 2025-04-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capybara_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default=None, upload_to='images/cat_img/'),
            preserve_default=False,
        ),
    ]
