# Generated by Django 5.2 on 2025-05-02 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capybara_categories', '0002_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Rubric')),
                ('order', models.SmallIntegerField(db_index=True, default=0, verbose_name='Order')),
                ('slug', models.SlugField(max_length=30, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='images/rubric_img/')),
            ],
        ),
        migrations.CreateModel(
            name='SubRubric',
            fields=[
            ],
            options={
                'verbose_name': 'Sub Rubric',
                'verbose_name_plural': 'Sub Rubrics',
                'ordering': ['super_rubric__order', 'super_rubric__name', 'order', 'name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('capybara_categories.rubric',),
        ),
        migrations.CreateModel(
            name='SuperRubric',
            fields=[
            ],
            options={
                'verbose_name': 'Super Rubric',
                'verbose_name_plural': 'Super Rubrics',
                'ordering': ['order', 'name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('capybara_categories.rubric',),
        ),
        migrations.AddField(
            model_name='rubric',
            name='super_rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_rubrics', to='capybara_categories.superrubric', verbose_name='Super Rubric'),
        ),
    ]
