# Generated by Django 5.2 on 2025-04-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capybara_tg_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(default='en', max_length=5, verbose_name='Language'),
        ),
    ]
