# Generated by Django 5.2 on 2025-05-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Name')),
                ('code', models.CharField(db_index=True, max_length=8, verbose_name='Code')),
                ('order', models.SmallIntegerField(db_index=True, default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['order'],
            },
        ),
    ]
