# Generated by Django 5.2 on 2025-04-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capybara_currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['order'], 'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(db_index=True, max_length=8, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='Order'),
        ),
    ]
